language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "Q8gnJUXbzVwxCtIhKqWQFOmEM9VyadmvHyAk2d/Sua6y0pGwvNuW03ftfgu9fc/U6EvUgtXP8pfJhIV8RqvRj7BcN7CthE2GMr4CJxJuy2G4o7LhNd0a0UiXjOUByVo/MPsoRA4S6hyfGsvMdjYeeY41zFdJWgjL9B39Lg7XhBoxkwThbgeco/Z5/vKdi0W4LWKp87mTNPOMGjgmYcpCkIUOTtA82dR35DIzhZGmjrgijpzX5NHctjci7N7SThosWqO194y2sS7twwiPMawfUXcdOu7XfAYErJvlpUbSmT2md038P+aB1AYCaH2oJhgQTlIkna9oADYBLoKae6FMgOK9NcYQW75O34pg1vC5XhPt3DIvDwz4dUEpi7k5mzHqg11BiCOghUMkQkjKs3/0nbct0Yae0wpxa4oP+DEBDzfRxcBBUfymNmD5OHwmIkJpC+MFcOYIqUF3X6zJYAuSzyUIr3icE2mRJWLDOqYOeiA2nwhNNJkAj0ZujOMDQ22xEVG/spNkRsI0CMiymIqNQBxFzM0KYtm3NntZbuJeJ309iKQ1S//wOWfpTIvR/2ulHaV4bJp472wHWM9tVHEmSt0Drsv4TB9RI2UR0rkvi6+Zk1oua5dJ+S5dqgzAhHFHmG3EnaQw1qoVngYtzmextmAKI+EqQn+n1Rq+TocPw3Y="
  - secure: "PB9fLx0TEh1CipXweDVfldLQKH8Sqq9Vvjdo7GlxAv3PdKiKdycH4rtHrCIgupdkTN0oAwHhbe7HwFKkG81x1IQRvOPytnNfHetcWZp8LJOljZUFPK8vax4NejY34VuMgwg6GoxeTmZaHvDY78vKs2GsyZjNUY1Zke+xWSOybVRYifBbAm/Py0cH2eiDNvAmvBPW94Ne/FqTdf2etUHSaqRVCZu90JVAbo7H/ytYRIU70550xTrqFSdq9c+clu5/64Ka+NVUNEzjNa2M0p/oivkB9yx9HZXsHSvxXveYSf4VL++dMl15/nnrRJ0ibp8Kg8Ld1hRRWIYeB/w34E8+Y6fgz1z6mQ5EPid5G6koOqQvCYO5/qStjVe4DusWviR+efo0gTw2UJdC9kTHgpvA2biUVyEnHXKyeCOPV0X/EodAV7Dq8idr5j5EorPJolNSjrEQpYGD3eZ71/od3jxgaFLW+RSj9KuTb22/VEDpZEUBzDmvgs0PGA7W+3kArldeXU+vlm7PSLhayCE0UStLRPXJooXd5UvxnBu+qYDi6BoEFobEU4gr4vvbeXvpHvwRefVHLBYLXjgA2dw+YVnh+Q/lv6z61aS+awK35an55mcFGkLMe+3ZfeBb8AVorrOjoJNVaSAuk4m2VqpOd/qDuf5WVDozZdKn2cUjk3b61JQ="
before_script:
- chmod +x ./script/cibuild
script:
- ./script/cibuild
after_success:
- find _site -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USERNAME:$FTP_PASSWORD ftp://waws-prod-am2-011.ftp.azurewebsites.windows.net/site/wwwroot/{}  \; | sed 's/_site\///g'
